<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP Assignment</title>
</head>
<body>
    <h1>Welcome to My PHP Application</h1>

    <?php
    echo "<p>This is a paragraph generated by PHP.</p>";

    // Output using <pre> for formatted text
    echo "<pre>";
    echo "Formatted text:\n";
    echo "Line 1\n";
    echo "Line 2\n";
    echo "Line 3\n";
    echo "</pre>";
    ?>

    <p>This is a static HTML paragraph.</p>
</body>
</html>